# Generated by Django 4.2 on 2025-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='ride',
            name='device_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
