# Generated by Django 4.2 on 2025-07-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_options_ride_device_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='device_time',
        ),
    ]
