# Generated by Django 4.2 on 2025-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_options_remove_ride_device_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='ride',
            name='device_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
