# Generated by Django 4.2 on 2025-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_options_ride_device_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
